FPPOPTS='$(DEFINE)GENIENX=64 $(DEFINE)GENIENY=32 $(DEFINE)GOLDSTEINNLONS=64 $(DEFINE)GOLDSTEINNLATS=32 $(DEFINE)GOLDSTEINNLEVS=16 $(DEFINE)GOLDSTEINNTRACS=19 '
MODULE_NAMES='plasim goldstein goldsteinseaice biogem atchem '
FPPOPTS2='$(DEFINE)USE_plasim $(DEFINE)USE_goldstein $(DEFINE)USE_goldsteinseaice $(DEFINE)USE_biogem $(DEFINE)USE_atchem '
