OUTROOT=/home/sulphurtuft/cgenie_output
CODEDIR=/home/sulphurtuft/cgenie.muffin
RUNTIME_ROOT=../../cgenie.muffin
RUNTIME_OUTDIR=.
EXPID=AOMTM.igcm16.RUN
FIXEDATMOSFILE=data_fixedatmos
GLIMMERFILE=data_glimmer.config
igcm_module=genie-igcm
BFGROOT=EMPTY
MODULE_NAMES='plasim goldstein goldsteinseaice biogem atchem '